"""Added orders table

Revision ID: 61cdc3e95b8e
Revises: 4ca6393774df
Create Date: 2024-11-07 15:15:46.978044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cdc3e95b8e'
down_revision = '4ca6393774df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gas_cylinder_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('price_paid', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['gas_cylinder_id'], ['gas_cylinders.id'], name=op.f('fk_orders_gas_cylinder_id_gas_cylinders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
