"""Added 3 fields to orders table

Revision ID: f4182f335992
Revises: 61cdc3e95b8e
Create Date: 2024-11-08 13:49:52.053282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4182f335992'
down_revision = '61cdc3e95b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('mpesa_receipt_number')

    # ### end Alembic commands ###
